-- Create site_analytics table for tracking visitor statistics
CREATE TABLE IF NOT EXISTS public.site_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_path TEXT NOT NULL,
    visited_at TIMESTAMPTZ DEFAULT NOW(),
    user_agent TEXT,
    ip_hash TEXT -- Optional: for unique visitor tracking
);

-- Index for performance on date ranges
CREATE INDEX IF NOT EXISTS idx_site_analytics_visited_at ON public.site_analytics (visited_at);

-- Set up RLS (Row Level Security)
ALTER TABLE public.site_analytics ENABLE ROW LEVEL SECURITY;

-- Allow public to insert (for tracking)
CREATE POLICY "Allow public tracking" ON public.site_analytics
    FOR INSERT WITH CHECK (true);

-- Allow authenticated admins to select
CREATE POLICY "Allow admin to view analytics" ON public.site_analytics
    FOR SELECT TO authenticated USING (true);
